## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [26]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples = np.random.normal(100, 15, 1000)
samples

array([107.37005782, 103.20202849,  68.68237823, 104.62808392,
        82.89052923,  87.02218425,  96.87390566, 119.23791148,
       115.72492597,  80.03052679, 110.17413638,  96.50075095,
        95.85339946,  90.49454016, 110.2747068 ,  94.4711567 ,
       105.15266727, 100.28964051,  98.44837953, 106.24053985,
        84.19394694, 111.10830316, 113.76700496,  83.79240836,
        90.83220502, 113.09237389,  99.01117438,  94.89662979,
        94.62411607,  79.440125  , 108.16620819,  91.74347231,
       101.71382139, 105.08553963, 132.54979005, 103.925558  ,
       102.12773713, 114.0262936 , 117.03945291,  99.08857425,
       102.06974452,  90.53261664, 105.84721132, 124.39710172,
       109.40020226, 113.44052892, 106.84184465, 104.88467756,
       108.11637266, 124.09051619, 111.55606933,  91.81560614,
       110.27155141, 117.09269435,  97.34373182, 104.94938978,
       110.54388449, 100.95785144,  90.99561207, 111.44860204,
       101.35657869,  85.12616217, 114.4444045 , 113.94998537,
       104.68503065, 104.34812998,  90.24591038, 109.71510543,
        95.79751426, 110.30306195, 102.15019346,  63.89578207,
        86.70711551,  73.66045944,  99.14220412,  90.32699477,
       107.78629415, 103.30239656, 103.93366187, 100.02753225,
        88.91451141,  96.89420232,  96.03270602, 105.93231468,
       134.0918146 , 103.53755877,  98.83989153, 103.13334308,
       129.9128129 , 118.44044977,  98.38088281, 114.73318949,
       105.81775335, 141.43804704,  96.92436768,  87.43670116,
       105.85397757, 101.59264278,  99.33719661, 110.53621772,
        91.16599363,  87.09766184,  95.412193  , 121.06145886,
        91.72232589,  88.03702457,  81.0792728 , 112.37279946,
       109.0585111 ,  75.43830498,  93.83660974, 106.31365483,
        93.32685092, 111.46615079,  68.1084957 ,  77.4354782 ,
       117.29835843,  99.33342213,  93.53175391, 108.43980011,
        87.97404402,  79.67585016, 133.92054669, 101.98135801,
       105.24797179,  93.25267587,  86.31826568, 126.7500142 ,
        92.72459352,  93.01090819,  98.6327839 , 104.08112965,
        89.57272613,  89.56228216, 136.27556003, 129.36008289,
        92.62594455, 127.44284793,  96.70191649,  95.1754773 ,
        96.25781651, 107.67695568,  75.34392184,  93.58122537,
        96.4340417 , 126.27688619, 101.7692757 ,  97.14271816,
       119.11732987, 117.15296166,  87.58656124,  94.12708626,
        95.41496778, 113.94362403,  96.25786622, 113.46483553,
       112.06987357, 118.97105168, 107.77786539, 125.21744162,
        82.32239321, 110.22834403, 105.9625141 , 105.17056375,
       116.87510316, 105.00709955, 107.72733682, 110.70760663,
       104.90063112,  86.91767689, 112.80717667,  92.78655155,
        78.36947367,  80.40801532, 100.6313458 , 106.17530411,
        81.02573508, 108.05674987,  93.90041392,  96.38648052,
       108.75572792,  98.41282402,  92.68311974,  90.15045635,
        87.43201306, 100.49621154, 113.80760933,  85.79819305,
        85.68426931, 101.07200662, 115.11979973,  99.42357741,
        99.83552737, 111.69807572,  79.61938801,  78.42285715,
        74.75250782,  85.65008148,  85.14670651,  94.74914178,
       111.25901655, 106.58589176,  69.11905874, 105.56681057,
       115.23424888,  79.95397937,  91.14647185, 111.59487346,
        97.82068122, 120.48361927, 115.99686829, 105.13578787,
       112.76357227,  86.32149145,  92.82266124, 113.21996795,
        79.04491143,  88.98784731,  93.74098849, 117.59058187,
        97.48116858, 119.04671389,  93.90885826, 121.13873344,
        93.67161021,  98.60460494, 101.46423427, 124.83740436,
        88.59194709,  97.86275268, 107.61489648, 107.90736959,
        88.54277839,  63.50799397, 121.17223132,  81.47182369,
        82.41695034, 109.42764329, 105.13202633,  98.1218832 ,
       101.8256367 , 130.78466443, 107.76222664,  96.21123268,
       107.51737096,  98.14669737,  99.76521845,  95.73069851,
       101.20276574, 109.86570967,  90.85087514,  87.26411642,
        84.25733766, 117.69558644,  96.59041342, 117.38970805,
        92.10734024,  90.81279492, 114.08711995,  87.84870792,
       101.85395747,  91.24618731, 112.70034802, 116.43248477,
        91.64512083,  90.87648463, 125.11747968,  92.4538679 ,
        99.22859636, 108.16300267, 115.62396128, 103.02077667,
        77.34911795,  91.9092061 ,  89.4432276 ,  97.34085032,
       108.5599376 ,  76.17803913, 117.74835999, 116.04685275,
        86.48937173,  85.19488199, 104.27129378, 133.92908767,
       104.4153314 ,  81.73434476,  69.63437366, 119.13959258,
       115.44644369,  75.19305926,  92.94380515,  87.37206502,
        91.80098546, 100.85541114,  81.81979799,  98.10057856,
       108.65548804,  93.03342784, 108.84276447,  86.77955225,
        95.52794268, 131.95223103,  96.32049828, 118.70770041,
       115.58214651,  89.03179118,  89.82458085, 108.73274948,
        95.71145168,  92.42762015, 100.96066214, 124.8971788 ,
        72.26584849, 103.062385  ,  90.75798478, 107.28469507,
       117.5948242 , 128.62214597, 108.20963266, 113.72350957,
        99.68980925,  95.19035072,  81.07022938,  99.73311942,
       109.58829107, 118.81213188,  91.13094843,  89.00784285,
       100.95524658, 107.51946837,  90.67727068,  90.30150347,
       115.26461922,  84.09773679, 118.07766203, 126.96779468,
        92.22720605, 119.82769666, 102.21788906,  92.56106019,
        93.46534217, 112.30165726, 111.7871958 ,  91.80634348,
        93.172923  , 103.29626643, 100.88250871, 131.39011997,
       102.81474562,  80.471516  , 107.42760298,  89.2128454 ,
       134.91555797, 101.844552  ,  89.43272517, 125.11811587,
       109.22399949,  84.68390353,  81.64356612, 120.92647122,
       107.26611608,  90.15915613,  96.24449029,  97.29188777,
       102.67944493, 108.54255064,  95.17382912,  99.72246509,
        88.7926711 , 100.82519825, 109.4102137 , 110.19604743,
       105.19751025,  86.81413518,  97.36589952,  70.18362528,
        75.18692744, 113.83513886, 107.37002195,  76.14734289,
       107.0879961 , 110.01440219,  79.68668132,  92.44193265,
        88.77330489,  87.24596489,  87.51028445, 106.95166254,
        85.26953842,  99.25105268,  86.24399702,  92.44021725,
        67.69917308,  83.75661564, 108.23339882, 110.72521573,
        90.42190994, 102.32507229,  88.58305532,  94.67167661,
       118.88915645, 111.63805612, 115.79980523,  74.37927042,
       111.19087408,  85.32473458,  91.70990917,  81.67989761,
        96.72626521, 113.16080323, 110.76754546,  87.54146036,
        81.45958865,  96.47377874,  96.07657954,  90.35836478,
       110.82520753, 104.35117733,  93.57303785,  86.68779877,
       105.16900341,  55.66244208, 104.95717942, 102.09473436,
       113.88816738, 115.0877956 ,  98.04908549,  63.04404768,
       116.40277257,  76.21466899, 120.3359106 , 101.1830808 ,
        78.22564624, 124.56353967, 128.35793083,  92.41966657,
       115.18095472,  80.8569398 ,  85.60694197, 100.1659041 ,
        64.42329419,  96.08746788,  82.59974276,  99.62297648,
       102.10102476,  92.43638265, 104.34550019, 100.16700957,
        82.92695605,  89.39927105, 102.64080237,  84.11023004,
        83.89661862, 103.4761847 , 102.86634617,  84.1085527 ,
       102.18536367, 105.16128694, 105.31640019, 136.0273654 ,
       119.95202001, 110.04797468,  84.1354079 , 109.41349157,
        83.3128257 , 126.06299705, 133.50025554,  83.69460284,
       103.96814265,  83.38296501, 112.69624294, 114.68498861,
        75.99456005, 124.81905105, 110.3106603 ,  99.88235184,
        88.95715028, 113.51240228, 105.52320078,  82.61570076,
        92.84603825, 125.70132219, 107.67025779, 108.60056702,
       121.55504845,  59.43776848,  78.57054321,  80.15088213,
       100.52609901, 101.99941548,  92.15871328,  97.73261339,
        85.49971718, 100.75833072, 104.61425463, 138.28359096,
        92.48682201, 101.6281629 ,  94.96837479, 115.33383089,
        81.60231547,  79.32009704, 106.34028644,  94.046386  ,
       107.74810887, 104.0615008 ,  99.69984013,  95.11024287,
        87.76161228, 100.10052367,  88.83278427, 109.44299947,
       101.55620446,  76.07977694, 101.12136042, 103.38695199,
        92.15079778,  91.49795223, 107.07001643,  87.77338093,
       106.36126571,  97.42582801, 135.00322653,  73.90008574,
       122.08361791, 122.93517153,  97.13012158,  94.3172322 ,
        92.72025462, 112.74305536,  84.63715838, 106.23431979,
        89.18054056, 126.5126736 , 102.02597892, 113.14338459,
        80.12400438,  92.48414159, 122.78719806,  73.70843245,
       119.82576561,  98.0204675 ,  94.58336937,  84.38035843,
       119.87693162,  94.6757348 , 101.01130701,  92.96461248,
        78.44089515,  96.75951929, 116.09988668, 124.7319395 ,
        99.59943892, 100.88746714,  98.41711835, 106.14962519,
        80.00781747, 108.9798564 , 129.31176148,  94.91776302,
        81.28369151, 119.86558716,  94.97495753, 118.07698404,
        96.81902497, 100.023693  ,  85.75785377, 124.04477878,
       100.0445084 ,  90.27001142,  95.40294396,  57.80317452,
        97.28982122,  94.10884659,  67.52217545,  83.93714397,
       101.81411509,  85.23254638, 104.2283509 , 120.747491  ,
       111.7037401 , 103.32488257,  63.57720934,  95.41182369,
       124.246589  ,  81.32851791, 124.3611037 , 103.17343658,
        79.86209331,  73.95242482,  74.10973689, 107.8221889 ,
       119.50875928,  82.5606982 ,  64.17665308,  87.8803403 ,
       111.76419978, 100.64416675,  86.4188959 , 100.13603207,
       102.56400868,  89.38514934, 103.42474729, 111.58256118,
        97.58267339,  90.27137231,  96.12304905,  92.17839732,
        84.79117761, 106.59664401, 111.81930393, 120.50684881,
        96.8557741 , 123.96865835,  98.1146072 , 110.10437168,
       106.36337567, 104.15009919,  94.46249824,  94.2725289 ,
        76.57779158, 105.57240375,  98.33867638, 109.19892627,
        98.53056829, 116.34765449, 103.89163078, 117.92035442,
        86.13882652, 125.32633152, 108.32523194,  90.94038294,
       122.21693959, 113.98339636, 109.120894  , 117.10111825,
        92.89381302, 129.33253123, 101.67444552,  81.23860312,
       119.80327156, 109.61331501,  82.05448991, 119.97273354,
        85.66241925,  95.05782983, 123.05285555,  85.55636927,
       112.45708951, 104.76250368,  76.60727806,  94.78030428,
       101.4889388 ,  80.41050268,  90.7893577 , 125.8073408 ,
        85.28215765,  94.26475737, 104.52006337, 110.70683354,
       111.70279608,  89.13194923,  99.11942001,  92.30998437,
       100.17477074, 127.65203009, 109.03603389, 100.53267923,
        76.56512368, 118.61506306,  84.22220935,  88.09412147,
       100.9054484 , 111.71483124, 103.37050545,  98.07209102,
       110.68258682,  78.23279707,  84.54438484,  86.61879274,
       102.84675417,  82.22460031, 111.08580915,  94.89538733,
        83.95980206,  88.0359281 ,  97.34844311,  76.34947281,
       109.25445852,  97.22677029, 112.85429927,  93.74042759,
        80.22324893, 106.52583196,  91.46685284, 104.5784355 ,
        77.82513898, 113.46494859,  81.66075656, 113.06799718,
       114.61651443,  94.96173222, 111.06092644,  91.53428559,
        95.88841163,  90.74918254,  80.19736256, 113.83199876,
        94.62659783, 101.56030588, 121.2567848 ,  80.78825563,
       102.14741066,  78.8471984 , 103.93840896, 107.62257034,
        76.8017117 ,  86.34031676, 116.10230216, 121.11197949,
        71.62387201, 107.63426209, 106.33429697, 119.3127299 ,
       105.47817821, 116.98299345, 102.4159928 ,  61.96116672,
       106.95788306, 113.45018556,  98.38672303, 120.10540444,
        75.17765785, 105.40666308, 108.13681606, 113.45029886,
       110.28170258,  60.63549344, 113.78474716, 143.87421096,
        99.27900165,  93.34812501,  95.17164324, 126.66632699,
       143.26290816, 127.87116985, 115.15647068, 109.36372506,
        93.35992484,  89.56775673, 128.45009373,  82.52265489,
       110.3536421 ,  81.54201265, 109.51599776,  94.29750644,
       101.44325992,  74.05441387, 112.28690828, 107.6979183 ,
        97.00569812,  80.56194423, 105.48875599, 101.7087952 ,
        96.9488232 ,  77.24648624, 108.66499336,  95.67963915,
       118.65982594,  99.09975772,  97.61451726, 116.67269328,
        80.95622537,  90.44032355,  91.2374323 ,  95.20380455,
       129.34295437, 119.36720995,  77.2296616 , 104.6492815 ,
       103.87213615,  87.60986994,  97.83357695, 118.33998484,
       108.28176992, 100.49852001, 115.95205446, 108.48642346,
        93.76824335, 110.32605854, 120.18826934, 134.71807977,
       115.87587154,  68.90004331, 115.38853764,  96.30173405,
       105.31260042,  93.47949813, 112.71067029, 105.10641426,
       112.09211708,  78.34460959,  91.42569222,  88.23564818,
       112.49724413, 119.92724486,  80.44888556,  91.59160639,
       109.13623181, 111.94449666,  82.91413408, 103.87044968,
       118.04868898, 112.49920326, 105.29676   , 111.47776853,
        83.94818339, 108.10592348, 129.01108923, 109.50158777,
       111.77601239, 113.09394592,  89.66041008,  86.67805931,
        92.72256215, 100.96164339, 114.78306687, 106.44557535,
        96.57336253, 107.21824938, 114.9686042 ,  86.31562284,
       104.23848806, 121.86547361, 116.49026844,  98.45902117,
        90.769515  , 109.866642  , 102.09395464,  82.31852682,
       114.82240924, 104.31356724, 104.7819743 ,  87.23192409,
       103.33363897, 100.91661876, 104.73485101, 103.26522624,
       100.25828987,  98.72677186, 106.47697187, 126.47213518,
        90.91235434, 115.5647602 , 117.61047061, 107.01273667,
        94.84663517, 111.19902246, 102.43999417,  99.81955747,
       120.63081534,  97.27448306, 115.44353907,  87.0389225 ,
       112.58356188, 110.73232043, 121.73587788, 113.50810563,
        88.23592182, 105.33371584, 100.11101171, 121.6829376 ,
        72.06992411,  85.16227532, 111.2757284 ,  92.27992143,
       114.05050459,  83.51542171,  98.95257952, 108.53305853,
       117.54540423, 135.99965431, 106.93919087,  88.72842965,
       100.00696057,  83.41109387, 120.66104965, 113.18713432,
        69.44189652, 102.70275932,  97.30124493, 118.8856407 ,
        82.58124691,  90.5309716 , 111.27243015,  58.62356292,
       103.90238729,  96.91225453,  99.20711752, 113.80155626,
       112.04737874, 119.87579146, 110.25014176, 101.1722097 ,
        90.88108548, 115.6138084 ,  87.11333607,  90.69628838,
       112.63425423,  82.13188845,  89.6592924 ,  88.14902769,
        76.98260843,  78.19781451,  99.79741994, 125.55952979,
        86.59484728, 113.98915113,  91.84973611, 109.21354364,
        99.57187601, 115.24350812,  99.82188213,  79.7561641 ,
       108.93669768,  75.88671752,  62.92566117,  87.90311706,
       111.08308794, 110.00337322,  89.91482346, 113.6743584 ,
        83.31138838, 104.66814304, 113.81488033, 116.66218674,
       114.56696297, 117.79682097, 100.75531702, 103.57779251,
       101.46242414, 116.35035783, 100.96734519, 106.63278712,
        99.00882601, 105.89965741,  93.83777193,  97.03759999,
       100.01764208,  93.17784927, 102.92425187, 111.54597333,
        94.02247451,  99.32775744, 102.77713723,  89.15382209,
       112.32272322, 126.1678056 , 120.96680047, 108.26988855,
        86.64856572,  87.65744148, 129.20199204,  95.97193726,
        89.89188393, 142.54498595,  86.28698258,  92.26086119,
       122.78780721, 102.00491375,  91.72063151, 113.90739279,
        81.54606295, 108.94367821,  94.55608873, 133.43773324,
       100.11347037,  98.54251233, 101.87144827,  97.91460992,
        91.95084009,  98.59517728,  93.72590463, 102.52221397,
        95.92350758, 107.30774497,  88.45221395,  90.70015236,
       105.70249002,  72.20824758, 105.56585834, 115.39137039,
       102.60171448,  98.72224909,  96.08643991,  81.1076145 ,
       100.90384978, 100.33416424, 103.33803411,  90.23458694])

Compute the **mean**, **median**, and **mode**

In [15]:
mean = samples.mean()
print("mean   :" , mean, )
median = np.median(samples)
print("median : ",median)
mode = sp.stats.mode(samples)
print("mode   :", mode)

mean   : 100.5530007452375
median :  100.79176448458554
mode   : ModeResult(mode=array([55.66244208]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [19]:
min = samples.min()
print("min :", min)
max = samples.max()
print("max :", max)
q1 = np.quantile(samples, .25)
print("q1 :", q1)
q3 = np.quantile(samples, .75)
print("q3 :", q3)
iqr = np.quantile(samples, .50)
print("iqr : ", iqr)

min : 55.66244207921135
max : 143.87421096040654
q1 : 90.73692499393975
q3 : 110.68864849877345
iqr :  100.79176448458554

Compute the **variance** and **standard deviation**

In [24]:
variance = samples.var()
print("variance: ", variance)
std_dev = samples.std()
print("std_dev :", std_dev)

variance:  212.9477610487781
std_dev : 14.592729732602399

Compute the **skewness** and **kurtosis**

In [27]:
from scipy import stats

In [32]:
skewness = sp.stats.skew(samples)
print("skewness :",skewness)
kurtosis = sp.stats.kurtosis(samples)
print("kurtosis :",kurtosis)

skewness : -0.028750096854409067
kurtosis : -0.021586738329131716

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [34]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [37]:
y = np.random.randint(10, size = 10)
y

array([0, 2, 1, 4, 5, 2, 2, 9, 4, 9])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [38]:
r = np.corrcoef(x, y, rowvar=False)
r

array([[1.        , 0.74107391],
       [0.74107391, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [39]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [44]:
r = x.corr(y, method = "pearson")
r

0.7586402890911867

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [45]:
rho = x.corr(y, method = "spearman")
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [46]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [47]:
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [48]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [50]:
r = tips.total_bill.corr(tips.tip, method = "pearson")
r

0.6757341092113641